name = "SpinDynamics"
uuid = "bb1a7079-d21b-44b1-9579-2045e0d16936"
authors = ["Javad Vahedi"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
